#!/usr/bin/env bash
# export-openapi.sh — snapshot the live OpenAPI spec to docs/openapi.{json,yaml}.
#
# The canonical spec is generated by the running app from the actual controllers,
# so it never drifts. This script just persists a copy for client codegen / the
# frontend. Run it with the app up:
#
#   docker compose up -d            # (or: mvn spring-boot:run)
#   ./scripts/export-openapi.sh
#
set -euo pipefail
HOST="${CARGOIQ_HOST:-http://localhost:8080}"
OUT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/docs"
mkdir -p "$OUT_DIR"

echo "→ fetching $HOST/v3/api-docs"
curl -fsS "$HOST/v3/api-docs"      | jq . > "$OUT_DIR/openapi.json"
echo "  ✓ $OUT_DIR/openapi.json"

echo "→ fetching $HOST/v3/api-docs.yaml"
curl -fsS "$HOST/v3/api-docs.yaml" > "$OUT_DIR/openapi.yaml"
echo "  ✓ $OUT_DIR/openapi.yaml"

echo "Done. Swagger UI: $HOST/swagger"
